server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.3:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.3:3306/seata_order?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

#feign:
#  hystrix:
#    enabled: false

logging:
  level:
    io:
      seata: info

#mybatis:
#  mapperLocations: classpath:top/liguapi/mapper/*.xml

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      serverAddr: 192.168.150.3:8848
      group: SEATA_GROUP
      namespace:
      cluster: default
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.150.3:8848
      namespace:
      group: SEATA_GROUP
      username: nacos
      password: nacos
      dataId: seataServer.properties







